### ISSUE TITLE
Retaining old messages

### ISSUE THREAD

**Issue by KrishnaPG** [crossbario/crossbar-examples#41]
Is it possible to publish the messages in "retain" mode (where, the subscribers who join late do not miss the earlier posted messages and get them immediately upon subscription). 

For example, publisher created with "retain" mode (and optional buffer length, say `n`), keeps track of the last `n` posted messages and pushes them immediately to all new subscribers as and when they signup.

It would be very useful function to support, as it helps in syncing the producer-consumer properly. 

MQTT is good example of where this is supported, and is very useful, especially in bridged/forwarded cluster scenarios.

**Comment by goeddea** [comment]
Crossbar.io and WAMP currently do not support any kind of message persistence. (There's a WAMP issue for this - https://github.com/wamp-proto/wamp-proto/issues/43).

Currently the way to go here is to e.g. have a component which subscribes to the messages, persists them, and which offers a procedure for newly connecting clients to request back messages (e.g. based on a timestamp).

Closing this issue here since it does not concern the crossbar examples.
