### ISSUE TITLE
registration details in wamp.registration.on_register meta event

### ISSUE THREAD

**Issue by KrishnaPG** [crossbario/crossbar-examples#42]
It would be useful if `on_register` meta event not only sends the registration ID, but also other registration details, such as the URI etc.

It looks like it is possible to get the required details from the registraion ID by making extra API calls, but it would be lot easier if the event itself sends that data as, say `kwargs` or some other (instead of forcing the user to make additional calls).

For example, for fail-over scenarios, such as the example shown [here](http://my-classes.com/2015/10/15/singleton-websocket-publisher-with-autobahn-pubsub-crossbar-io-meta-events/#file-autobahn-singleton-pubsub-server-js-L58), monitoring the pairs `on_register` and `unregister` can help decide the monitoring function to decide if any action is needed or not (e.g. restart the failed server) without having to make additional calls (burdening the server and also causing latency).

**Comment by goeddea** [comment]
There's always a balance to be struck between keeping wire traffic down and passing information which avoids additional requests. 

The place to discuss this is in the WAMP protocol repository - https://github.com/wamp-proto/wamp-proto

Contributions there are highly welcome.

Closing this here since it does not concern the Crossbar examples.
